repos:
  - repo: local
    hooks:
      - id: super-linter-changed
        name: Super-Linter (changed files)
        entry: bash .githooks/pre-push.sh
        language: system
        always_run: true

